add Windows command line support

diff --git a/src/scripts/c/unix/txl2c b/src/scripts/c/unix/txl2c
--- a/src/scripts/c/unix/txl2c
+++ b/src/scripts/c/unix/txl2c
@@ -26,7 +26,7 @@ case `uname -s` in
     CYGWIN*|MSYS*|MINGW64*)
         CC="$CC -Wl,--stack,0x20000000";;
     *)
-        ;;
+	;;
 esac
 
 # Decode TXL program name and options
@@ -35,17 +35,17 @@ TXLOPTIONS=""
 while [ "$1" != "" ]
 do
     case "$1" in
-        *.[Tt]xl)
-                TXLPROG="$1"
-                ;;
-        -help)
-                echo "Usage:  txlc [txloptions] txlprog.txl" 1>&2
-                echo "('txl -help' for TXL options)" 1>&2
-                exit 99
-                ;;
-        *) 
-                TXLOPTIONS="$TXLOPTIONS $1"
-                ;;
+	*.[Tt]xl)
+		TXLPROG="$1"
+		;;
+	-help)
+		echo "Usage:  txlc [txloptions] txlprog.txl" 1>&2
+		echo "('txl -help' for TXL options)" 1>&2
+		exit 99
+		;;
+	*) 
+		TXLOPTIONS="$TXLOPTIONS $1"
+		;;
     esac
     shift
 done
@@ -77,28 +77,25 @@ if [ ! -r $TXLNAME.ctxl ]
 then
     if [ -r Txl/$TXLNAME.ctxl ]
     then
-        /bin/mv Txl/$TXLNAME.ctxl $TXLNAME.ctxl
+	/bin/mv Txl/$TXLNAME.ctxl $TXLNAME.ctxl
     else 
-        if [ -r txl/$TXLNAME.ctxl ]
-        then
-            /bin/mv txl/$TXLNAME.ctxl $TXLNAME.ctxl
-        else
-            echo "TXL compile failed" 1>&2
-            exit 99
-        fi
+	if [ -r txl/$TXLNAME.ctxl ]
+	then
+	    /bin/mv txl/$TXLNAME.ctxl $TXLNAME.ctxl
+	else
+	    echo "TXL compile failed" 1>&2
+	    exit 99
+	fi
     fi
 fi
 
 # Convert TXLVM byte code to initialized C byte array
 $TXLLIB/txlcvt.x $TXLNAME.ctxl
 
-# Compile and link with TXLVM
-$CC -O -w -o $TXLNAME.x $TXLLIB/txlmain.o $TXLLIB/txlvm.o  ${TXLNAME}_TXL.c -lm
-
 # Clean up
-/bin/rm -f $TXLNAME.ctxl Txl/$TXLNAME.ctxl txl/$TXLNAME.ctxl ${TXLNAME}_TXL.* 2> /dev/null
+/bin/rm -f $TXLNAME.ctxl Txl/$TXLNAME.ctxl txl/$TXLNAME.ctxl 2> /dev/null
 
 # Finish clean
 exit 0
 
-# Revised 25.4.24
+# Revised 17.5.24
